BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EVENTS" (
	"id"	INTEGER,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"event_timestamp"	BIGINT NOT NULL,
	"repeats"	TEXT,
	"where_address"	TEXT NOT NULL,
	"where_map_url"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "BLOG" (
	"id"	INTEGER,
	"title"	TEXT NOT NULL,
	"content"	TEXT NOT NULL,
	"date"	DATE NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
